title: Ma Bloh
author: Moreno Esparza JA
email: jamoreno83@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is ans example

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  baba # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
